# Generated by Django 3.2.7 on 2021-09-25 07:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20210925_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 7, 45, 19, 178601, tzinfo=utc)),
        ),
    ]
