# Generated by Django 3.2.7 on 2021-09-25 09:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20210925_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 9, 46, 18, 914425, tzinfo=utc)),
        ),
    ]
