# Generated by Django 3.2.7 on 2021-09-25 14:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_auto_20210925_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 14, 57, 15, 855402, tzinfo=utc)),
        ),
    ]
