# Generated by Django 3.2.7 on 2021-09-26 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_auto_20210926_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 26, 13, 45, 12, 264983, tzinfo=utc)),
        ),
    ]
