# Generated by Django 3.2.7 on 2021-09-27 14:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0022_auto_20210926_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 27, 14, 50, 14, 745780, tzinfo=utc)),
        ),
    ]
