# Generated by Django 3.2.7 on 2021-09-28 06:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_auto_20210928_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 6, 18, 26, 650319, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
