# Generated by Django 3.2.7 on 2021-09-28 07:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0025_auto_20210928_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 7, 24, 22, 322735, tzinfo=utc)),
        ),
    ]
