# Generated by Django 3.2.7 on 2021-09-29 08:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0033_auto_20210929_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 8, 3, 56, 371430, tzinfo=utc)),
        ),
    ]
