# Generated by Django 3.2.7 on 2021-09-29 11:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0034_alter_post_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='permission',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 11, 20, 59, 669900, tzinfo=utc)),
        ),
    ]
