# Generated by Django 3.2.7 on 2021-09-29 15:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0035_auto_20210929_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 29, 15, 37, 57, 878155, tzinfo=utc)),
        ),
    ]
